App01Menus/urls.py
from django.contrib import admin
from django.urls import path
from .views import *

app_name = 'App01Menus'

urlpatterns = [
    # path('menu/', menu, name='menu'),
    # path('detail/<int:pk>', detail, name='detail'),
]

Risto/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import *
from App01Menus.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',home, name='home'),
    # path('risto/',include('App01Menus.urls', namespace='risto') )
    path('menu/', menu, name='menu'),
    path('detail/<int:pk>', detail, name='detail'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

App01Menus/models.py
from django.db import models
import qrcode
from io import BytesIO
from django.core.files import File
from PIL import Image, ImageDraw



# Create your models here.

class Familia(models.Model):
    name = models.CharField(max_length=200)
    def __str__(self):
        return f'{self.name}'

class Producto(models.Model):
    name         = models.CharField(max_length=200,null=False,blank=False)
    description  = models.TextField(max_length=500, blank=True, null=True)
    tipo         = models.ForeignKey(Familia,on_delete=models.CASCADE, null=False, blank=False)
    pu           = models.IntegerField(default=0)
    image        = models.ImageField(upload_to='images/products/', null=True, blank=True)

    def __str__(self):
        return f'{self.name}'

class Website(models.Model):
    name = models.CharField(max_length=200)
    qr_code = models.ImageField(upload_to='qr_codes', blank=True)

    def __str__(self):
        return f'{self.name}'
    
    def save(self, *args, **kwargs):
        qrcode_img  = qrcode.make(self.name)
        canvas      = Image.new('RGB',(290,290),'white')
        draw        = ImageDraw.Draw(canvas)
        canvas.paste(qrcode_img)
        fname       = f'qr_code-{self.name}.png'
        buffer      = BytesIO()
        canvas.save(buffer,'PNG')
        self.qr_code.save(fname,File(buffer),save=False)
        canvas.close()
        super().save(*args, **kwargs)

App01Menus/views.py
from django.shortcuts import render, get_object_or_404 as goo404
from .models import *
# Create your views here.

def home(request):
     qr = goo404(Website,pk=1)
     return render(request, 'home.html', locals())

def menu(request):
    familias = Familia.objects.all()
    productos = Producto.objects.all()
    familias_no_vacias=()
    y=list(familias_no_vacias)
    for i in familias:
        count=0
        for j in productos:
            if j.tipo.name==i.name:
                count=+1
        if count!=0:
            y.append(i.name)

    print('Familias ===> ', y)
    qr = goo404(Website,pk=1)
    
    return render(request,'Menu.html',locals())

def detail(request,pk):
    qr = goo404(Website,pk=1)
    producto = Producto.objects.get(pk=pk)
    return render(request,'Detail.html',locals())

Risto/views.py
from django.shortcuts import render
from App01Menus.models import *

# Create your views here.

# def home(request):
#      qr = Website.objects.get(pk=1)
#      return render(request, 'App01Menus:home', locals())

App01Menus/templates/Detail.html
{% extends "base.html" %}
{% load static %}


{% block title %}Detail{% endblock %}

{% block content %}


<div class="card ">

    <div class="card-header hstack gap-1 ">
        <div class="col col-md-2"><img class="card-img-top img-thumbnail" src="{% static 'general/logo SUMAQ.jpg'%}" alt="Image not found" ></div>
        <div class="vr"></div>
        <div class="col col-md-4"><h2><strong>&nbsp;&nbsp;&nbsp;Detalle  </strong></h2></div>
        <div class="vr"></div>
        <div class="col col-md-1"><img src='{{qr.qr_code.url}}' width='150' height='150'></div>
        <div class="vr"></div>
        <div class="col col-md-1 text-center"><h4>{% now "d-m-Y" %}</h4></div>
        <div class="vr"></div>
        <div class="col col-md-4 text-center"><h2><a href="{% url 'menu' %}" class="btn btn-primary"><i class="bi bi-arrow-bar-left"></i>&nbsp;&nbsp;Menú</i></a></h2></div>
    </div> <!-- /END card-header -->

  <div class="card-body">      

      <div class="row">

        <div class="col-sm-2">
          <div Image class="input-group col-md-2">
            {% if producto.image %}
            <a href="{{producto.image.url}}" class='btn btn-secondary'>
              <div class="card" style="height:auto; width: 12rem">
                <img class="img-thumbnail" src="{{producto.image.url}}" alt="No image" title='Ver imagen' >
              </div>
            </a>
            {% else%}
            {% endif%}
              <a href="#" target="_blank" class='btn btn-warning' title='Editar imagen'>  <i class="fas fa-pen"></i> </a> 
          </div>
        </div>

        <div class="col-sm-4 ">
          <div Name class="col mt-3 form-floating">
            <input value='{{producto.name}}'  type="text" class="form-control" id="name" name="name" placeholder="name" required autofocus>
            <label for="name" class="form-label">Nombre </label>
          </div>

          <div familia class="col mt-3">
            <label for="familia" class="form-label">Familia</label>
            <div class="input-group">
              <input  value='{{producto.tipo.name}}' type="text" class="form-control" id="familia" name="familia" disabled >
              
              <!-- Button trigger modal -->
                <button type="button" class="btn btn-warning" data-bs-toggle="modal" data-bs-target="#exampleModalUpdate{{producto.id}}" title="Editar familia de producto ">
                    <i class="fas fa-pen"></i>
                </button>
            </div>
          </div>

          {% comment %} <div status class="col mt-3">
            <label for="bin" class="form-label">Estado</label>
            <select class="form-control" name="status" id="status" required>
              <option value="{{producto.status}}" selected > {{producto.status}} - {{producto.get_status_display}} </option>

              {% if producto.status == "D" %} {% else %} <option value="D" > D - Disponible </option> {% endif%}
              {% if producto.status == "R" %} {% else %} <option value="R" > R - Reservado </option> {% endif%}
              {% if producto.status == "O" %} {% else %} <option value="O" > O - En Obra </option> {% endif%}
              {% if producto.status == "M" %} {% else %} <option value="M" > M - Mantención </option> {% endif%}
              {% if producto.status == "B" %} {% else %} <option value="B" > B - De Baja </option> {% endif%}

            </select>
          </div> {% endcomment %}
        </div>

        <div class="col-md-2">

          {% comment %} <div BIN class="col mt-3">
            <label for="bin" class="form-label">BIN</label>
            <input value='{{producto.bin}}' type="text" class="form-control" id="bin" name="bin" disabled >
          </div> {% endcomment %}

          <div PU class="col mt-3">
            <label for="pu" class="form-label">Precio Unitario (CLP/HM)</label>
            <input value='{{producto.pu}}' type="text" class="form-control" id="pu" name="pu">
          </div>

          {% comment %} <div Ubicacion class="col mt-3">
            <label for="ubicación" class="form-label">Ubicación</label>
            <input value='{{producto.ubicación}}' type="text" class="form-control" id="ubicación" name="ubicación">
          </div> {% endcomment %}

        </div>

        <div class="col-md-4">
          <div Accordion class="accordion col mt-3" id="accordionPanelsStayOpenExample">
            
            <div class="accordion-item">
              <h2 class="accordion-header">
                <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseOne" aria-expanded="false" aria-controls="panelsStayOpen-collapseOne">
                  Descripción
                </button>
              </h2>
              <div id="panelsStayOpen-collapseOne" class="accordion-collapse collapse">
                <div class="accordion-body">
                  <textarea value='{{producto.description}}'  type="text" class="form-control" id="description" name="description" rows="5">{{producto.description}}</textarea>
                </div>
              </div>
            </div>
            
            {% comment %} <div class="accordion-item">
              <h2 class="accordion-header">
                <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseTwo" aria-expanded="false" aria-controls="panelsStayOpen-collapseTwo">
                  Otros Detalles
                </button>
              </h2>
              <div id="panelsStayOpen-collapseTwo" class="accordion-collapse collapse">
                <div class="accordion-body">
                  <strong>Peso (kg) </strong> 
                  <input class="form-control" type="text" value='{{producto.pesoKg}}' id="peso" name="peso">
                  <hr>
                  <strong>Color </strong>
                  <input class="form-control" type="text" value='{{producto.color}}' id="color" name="color">
                </div>
              </div>
            </div> {% endcomment %}
            
            {% comment %} <div class="accordion-item">
              <h2 class="accordion-header">
                <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseThree" aria-expanded="false" aria-controls="panelsStayOpen-collapseThree">
                  Fabricante y Proveedores
                </button>
              </h2>
              <div id="panelsStayOpen-collapseThree" class="accordion-collapse collapse">
                <div class="accordion-body">
                  <strong>Fabricado por   : </strong> {{producto.maker}}
                  <br>
                  <strong>Distribuido por : </strong>
                  <ul class="list-group list-group-flush">
                    {%for supp in producto.suppliers.values %}
                    <li class="list-group-item">
                      &nbsp;&nbsp;{{ supp.name }}
                      <span class="badge text-bg-danger rounded-pill">{{ supp.id }}</span>
                    </li>
                    {% endfor %}
                  </ul>
                </div>
              </div>
            </div> {% endcomment %}

          </div>

          {% comment %} <div Bt Grabar class="col mt-3">
            <button class="btn btn-primary" type="submit"><i class="bi bi-cloud-arrow-up" title='Update Material'></i>&nbsp;&nbsp;Actualizar</i></button>

            <a {% if producto.dataSheet %}href="{{producto.dataSheet.url}}"{% endif %}class='btn btn-secondary' target="_blank" title='Ver Hoja de Datos y Seguridad'> Ver HDD </a>
          </div> {% endcomment %}

        </div>

      </div>

  </div> <!-- /END Card Body -->


  </form>
</div> <!-- /END CARD -->




{% endblock %}

App01Menus/templates/Menu.html
{% extends "base.html" %}
{% load static %}


{% block title %}Menu{% endblock %}

{% block content %} 


<div class="card">
  
    <div class="card-header hstack gap-1 ">
        <div class="col col-md-2"><img class="card-img-top img-thumbnail" src="{% static 'general/logo SUMAQ.jpg'%}" alt="Image not found" ></div>
        <div class="vr"></div>
        <div class="col col-md-4"><h2><strong>&nbsp;&nbsp;&nbsp;Menu  </strong></h2></div>
        <div class="vr"></div>
        <div class="col col-md-1"><img src='{{qr.qr_code.url}}' width='150' height='150'></div>
        <div class="vr"></div>
        <div class="col col-md-1 text-center"><h4>{% now "d-m-Y" %}</h4></div>
        <div class="vr"></div>
        <div class="col col-md-4 text-center"><h2><a href="{% url 'home' %}" class="btn btn-primary"><i class="bi bi-arrow-bar-left"></i>&nbsp;&nbsp;Home</i></a></h2></div>
    </div> <!-- /END card-header -->
  
    <div class="card-body">
            
        {% for j in y %}
        <p> <h2><strong>{{j}}</strong></h2> </p>
        <div class="card-group m-1 p-3">
            {% for i in productos %}

                {% if i.tipo.name == j %}
                
                    <div class="card border-danger m-2 p-2 " style="max-width: 450px;">
                        <div class="row gx-1">
                            <div class="col-md-4">
                            <img src="{{i.image.url}}"  class="img-fluid rounded-start" alt="...">
                            </div>
                            <div class="col-md-8">
                            <div class="card-body text-danger">
                                <h5 class="card-title">{{i.name}}</h5>
                                <p class="card-text">{{i.description}}</p>
                                <p class="card-text"><strong>$ {{i.pu}}</strong></p>
                                <a href="{% url 'detail' i.id %}" class="btn btn-danger">Ver detalle</a>
                            </div>
                            </div>
                        </div>
                    </div>
                    
                {% endif %}
            
            {% endfor %}                
        </div>
        {% endfor %}
    </div>

</div>

{% endblock %}

App01Menus/templates/home.html
{% extends "base.html" %}
{% load static %}
{% comment %} {% load humanize %} {% endcomment %}

{% block title %}HOME{% endblock %}

{% block content %} 



<main class="container py-5">
	<section class="card content">
		<h6 class="display-1 card-title text-center">RISTO by ORDERED</h6>
		<hr>
		<div class="row" data-masonry='{"percentPosition": true }'>
				<div class="col-sm-6 col-lg-4 mb-4">
						<div class="card">
								<img class="bd-placeholder-img card-img-top" width="100%" height="200"  src="https://res.cloudinary.com/dtcskupwr/image/upload/v1665156318/surfpichi_z810fp.jpg" role="img" aria-label="Placeholder: Image cap" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#868e96"/><text x="50%" y="50%" fill="#dee2e6" dy=".3em"></text></img>
								<div class="card-body">
										{% comment %} {% if user.is_authenticated %}
										<p class="card-text"><strong>
												Bienvenido {{user.username|upper}} a tu comunidad regional!!!
										</strong></p>
										{% else%} {% endcomment %}
										<h5 class="card-title">Nuestros orígenes</h5>
										<p class="card-text"> 
												{% comment %} <a class="btn btn-primary" href="{% url 'signin'%}"> Ingresa </a> {% endcomment %}
										</p>
										{% comment %} {% endif %} {% endcomment %}
								</div>
						</div>
				</div>
				
				<div class="col-sm-6 col-lg-4 mb-4">
						<div class="card p-3">
								<figure class="p-3 mb-0">
										<blockquote class="blockquote">
											<div class="w-50"><h2><strong>&nbsp;&nbsp;&nbsp;Menu <img src='{{qr.qr_code.url}}' width='150' height='150'> </strong></h2></div>
										</blockquote>
										{% comment %} {% if user.is_authenticated %}
										{% else%}
										<figcaption class="blockquote-footer mb-0 text-muted">
												<a class="btn btn-primary" href="{% url 'signup'%}"> Registrate </a>
										</figcaption>
										{% endif %} {% endcomment %}
								</figure>
						</div>
				</div>

				<div class="col-sm-6 col-lg-4 mb-4">
						<div class="card">
								<img class="bd-placeholder-img card-img-top" width="100%" height="200" xmlns="http://www.w3.org/2000/svg" src="https://res.cloudinary.com/dtcskupwr/image/upload/v1663793216/cld-sample-5.jpg" role="img" aria-label="Placeholder: Image cap" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#868e96"/><text x="50%" y="50%" fill="#dee2e6" dy=".3em"></text></img>
								<div class="card-body">
										<h5 class="card-title">Contáctanos!!</h5>
										<p class="card-text">
												{% comment %} <a class="btn btn-primary" href="{% url 'contactar'%}"> Invita </a> {% endcomment %}
										</p>
										<p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
								</div>
						</div>
				</div>
				
				<div class="col-sm-6 col-lg-4 mb-4">
						<div class="card text-bg-primary text-center p-3">
								<figure class="mb-0">
										<blockquote class="blockquote">
												<a class="btn btn-danger btn-block active " href="{% url 'menu'%}" role="button"> Ver Menu </a>
										</blockquote>
										{% comment %} {% if user.is_authenticated %}
												<p class="card-text"></p>
														<a class="btn btn-primary btn-block active " href="{% url 'publica'%}" role="button"> ⚽ 🎃  🎪  🦺  👠  🎯 </a>
												</p>
										{% endif %} {% endcomment %}
								</figure>
						</div>
				</div>
				
				<div class="col-sm-6 col-lg-4 mb-4">
						<div class="card text-center">
								<div class="card-body">
										{% comment %} {% if user.is_authenticated %}
												<a class="btn btn-xl " href="{% url 'busca'%}" role="button">
														<h5 class="card-title">Aquí encontrarás de todo! 🔎  </h5>
												</a>
										{% endif %} {% endcomment %}
								</div>
						</div>
				</div>

				<div class="col-sm-6 col-lg-4 mb-4">
						<div class="card">
								<img class="bd-placeholder-img card-img-top" width="100%" height="200" xmlns="http://www.w3.org/2000/svg" src="https://res.cloudinary.com/dtcskupwr/image/upload/v1663793215/cld-sample-3.jpg" role="img" aria-label="Placeholder: Image cap" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#868e96"/><text x="50%" y="50%" fill="#dee2e6" dy=".3em"></text></img>
						</div>
				</div>

				<div class="col-sm-6 col-lg-4 mb-4">
						<div class="card p-3 text-end">
								<figure class="mb-0">
										<blockquote class="blockquote">
												<p> Artesanos de Machalí </p>
										</blockquote>
										<figcaption class="blockquote-footer mb-0 text-muted">
												Someone famous in <cite title="Source Title">Source Title</cite>
										</figcaption>
								</figure>
						</div>
				</div>

				<div class="col-sm-6 col-lg-4 mb-4">
						<div class="card">
								<div class="card-body">
										<h5 class="card-title">Card title</h5>
										<p class="card-text">This is another card with title and supporting text below. This card has some additional content to make it slightly taller overall.</p>
										<p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
								</div>
						</div>
				</div>

		</div>
	</section>
</main>


{% endblock content %} 

templates/home.html
{% extends "base.html" %}
{% load static %}
{% comment %} {% load humanize %} {% endcomment %}

{% block title %}HOME{% endblock %}

{% block content %} 



<main class="container py-5">
	<section class="card content">
		<h6 class="display-1 card-title text-center">RISTO by ORDERED</h6>
		<hr>
		<div class="row" data-masonry='{"percentPosition": true }'>
				<div class="col-sm-6 col-lg-4 mb-4">
						<div class="card">
								<img class="bd-placeholder-img card-img-top" width="100%" height="200"  src="https://res.cloudinary.com/dtcskupwr/image/upload/v1665156318/surfpichi_z810fp.jpg" role="img" aria-label="Placeholder: Image cap" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#868e96"/><text x="50%" y="50%" fill="#dee2e6" dy=".3em"></text></img>
								<div class="card-body">
										{% comment %} {% if user.is_authenticated %}
										<p class="card-text"><strong>
												Bienvenido {{user.username|upper}} a tu comunidad regional!!!
										</strong></p>
										{% else%} {% endcomment %}
										<h5 class="card-title">Nuestros orígenes</h5>
										<p class="card-text"> 
												{% comment %} <a class="btn btn-primary" href="{% url 'signin'%}"> Ingresa </a> {% endcomment %}
										</p>
										{% comment %} {% endif %} {% endcomment %}
								</div>
						</div>
				</div>
				
				<div class="col-sm-6 col-lg-4 mb-4">
						<div class="card p-3">
								<figure class="p-3 mb-0">
										<blockquote class="blockquote">
												<p>Perú</p>
										</blockquote>
										{% comment %} {% if user.is_authenticated %}
										{% else%}
										<figcaption class="blockquote-footer mb-0 text-muted">
												<a class="btn btn-primary" href="{% url 'signup'%}"> Registrate </a>
										</figcaption>
										{% endif %} {% endcomment %}
								</figure>
						</div>
				</div>

				<div class="col-sm-6 col-lg-4 mb-4">
						<div class="card">
								<img class="bd-placeholder-img card-img-top" width="100%" height="200" xmlns="http://www.w3.org/2000/svg" src="https://res.cloudinary.com/dtcskupwr/image/upload/v1663793216/cld-sample-5.jpg" role="img" aria-label="Placeholder: Image cap" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#868e96"/><text x="50%" y="50%" fill="#dee2e6" dy=".3em"></text></img>
								<div class="card-body">
										<h5 class="card-title">Contáctanos!!</h5>
										<p class="card-text">
												{% comment %} <a class="btn btn-primary" href="{% url 'contactar'%}"> Invita </a> {% endcomment %}
										</p>
										<p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
								</div>
						</div>
				</div>
				
				<div class="col-sm-6 col-lg-4 mb-4">
						<div class="card text-bg-primary text-center p-3">
								<figure class="mb-0">
										<blockquote class="blockquote">
												<a class="btn btn-danger btn-block active " href="{% url 'App01Menus:menu'%}" role="button"> Ver Menu </a>
										</blockquote>
										{% comment %} {% if user.is_authenticated %}
												<p class="card-text"></p>
														<a class="btn btn-primary btn-block active " href="{% url 'publica'%}" role="button"> ⚽ 🎃  🎪  🦺  👠  🎯 </a>
												</p>
										{% endif %} {% endcomment %}
								</figure>
						</div>
				</div>
				
				<div class="col-sm-6 col-lg-4 mb-4">
						<div class="card text-center">
								<div class="card-body">
										{% comment %} {% if user.is_authenticated %}
												<a class="btn btn-xl " href="{% url 'busca'%}" role="button">
														<h5 class="card-title">Aquí encontrarás de todo! 🔎  </h5>
												</a>
										{% endif %} {% endcomment %}
								</div>
						</div>
				</div>

				<div class="col-sm-6 col-lg-4 mb-4">
						<div class="card">
								<img class="bd-placeholder-img card-img-top" width="100%" height="200" xmlns="http://www.w3.org/2000/svg" src="https://res.cloudinary.com/dtcskupwr/image/upload/v1663793215/cld-sample-3.jpg" role="img" aria-label="Placeholder: Image cap" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#868e96"/><text x="50%" y="50%" fill="#dee2e6" dy=".3em"></text></img>
						</div>
				</div>

				<div class="col-sm-6 col-lg-4 mb-4">
						<div class="card p-3 text-end">
								<figure class="mb-0">
										<blockquote class="blockquote">
												<p> Artesanos de Machalí </p>
										</blockquote>
										<figcaption class="blockquote-footer mb-0 text-muted">
												Someone famous in <cite title="Source Title">Source Title</cite>
										</figcaption>
								</figure>
						</div>
				</div>

				<div class="col-sm-6 col-lg-4 mb-4">
						<div class="card">
								<div class="card-body">
										<h5 class="card-title">Card title</h5>
										<p class="card-text">This is another card with title and supporting text below. This card has some additional content to make it slightly taller overall.</p>
										<p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
								</div>
						</div>
				</div>

		</div>
	</section>
</main>


{% endblock content %} 